### PR TITLE
Expose additional functions from zookeeper library.

### PR DESCRIPTION
**Pull request by thegedge**
In removing etcd from locutus and moving over to zookeeper, I'll need most of the methods from the zookeeper package.

@marc-barry

### CODE REVIEW

**Comment by marc-barry** [comment]
LGTM. :ship:

**Comment by marc-barry** [comment]
@Sirupsen We are adding to https://github.com/Shopify/gozk-recipes as it is going to be used by Locutus, Borg and it is used in `bgpalived`. Thus, it would be great if you could also use it for service discovery and do PR's for any missing functionality you run into.

**Comment by sirupsen** [comment]
Sweet :-) @thegedge would you mind doing th tedious work of copying the signatures of the rest of the functions from upstream as well? :see_no_evil:

**Comment by thegedge** [comment]
Sure! I can approach this in two ways: embedding `zookeeper.Conn` in `session.ZKSession` or replicating the the `*zookeeper.Conn` interface in our library. The former will save a lot of unnecessary writing and call forwarding, but will require you to go to the `gozk` godoc page to know what you can do with a `session.ZKSession`. Any preference?

**Comment by sirupsen** [comment]
Embedding sounds good in my book! :sparkles: But your argument against it makes sense too. On that note you can also say that the library hasn't changed in years (and the API hasn't either) so it's unlikely to ever change. I'll leave it up to you :)

**Comment by thegedge** [comment]
Updated. After talking with Marc I decided to go with replicating the interface. It gives us an opportunity to add a better abstraction on top of the underlying `*zookeeper.Conn` struct (mostly with regards to producing nicer events for watches).

I also removed the named returns since we're not using them and I think they're all fairly obvious.

**Comment by sirupsen** [comment]
Ship :) I'd like to use this today

**Comment by thegedge** [comment]
Okay, good to ship now. Was missing a few `zookeeper.*` package references.

**Comment by sirupsen** [comment]
:clap:

**Comment by marc-barry** [comment]
Excellent. Thanks.

**Pull request merged**
